config/routes.rb
Rails.application.routes.draw do

  get '/play', to: "games#play"
  post '/scores', to: "games#scores"
  get '/', to: "games#play"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
require 'json'
require 'open-uri'

class GamesController < ApplicationController
  def play
    @letters = (Array.new(10) { ('A'..'Z').to_a.sample }).join(" ")
    @time_now = Time.now
  end

  def scores
    @letters = params[:letters].split(" ")
    @answer = params[:answer]
    @start_time = params[:start_time].to_time
    @end_time = Time.now
    @result = run_game(@answer, @letters, @start_time, @end_time)
  end


private

  def included?(guess, grid)
    guess.chars.all? { |letter| guess.count(letter) <= grid.count(letter) }
  end

  def compute_score(attempt, time_taken)
    time_taken > 60.0 ? 0 : attempt.size * (1.0 - time_taken / 60.0)
  end

  def run_game(attempt, grid, start_time, end_time)
    result = { time: end_time - start_time }

    score_and_message = score_and_message(attempt, grid, result[:time])
    result[:score] = score_and_message.first
    result[:message] = score_and_message.last

    result
  end

  def score_and_message(attempt, grid, time)
    if included?(attempt.upcase, grid)
      if english_word?(attempt)
        score = compute_score(attempt, time)
        [score, "well done"]
      else
        [0, "not an english word"]
      end
    else
      [0, "not in the grid"]
    end
  end

  def english_word?(attempt)
    response = open("https://wagon-dictionary.herokuapp.com/#{attempt}")
    json = JSON.parse(response.read)
    return json['found']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/views/games/play.html.erb
<h1>******** Welcome to the longest word-game!********</h1>
<h2>Here is your grid:</h2>
<h2><%=@letters%></h2>





<form action="/scores" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <label for="question">Please input your word</label>
  <input type="hidden" name="start_time" value='<%=@time_now%>'>
  <input type="hidden" name="letters" value='<%=@letters%>'>
  <input type="text" id="question" name="answer" placeholder="Answer">
  <input type="submit" value="Go on!">
</form>

app/views/games/scores.html.erb
<h2>Random letters : <%= @letters %></h2>
<h2>Total Time : <%= @result[:time].round(2) %> seconds</h2>
<h2> Score : <%=@result[:score].round(2)%></h2>
<h2><%=@result[:message]%></h2>


<%= link_to "Play a new game!", play_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>